name: "Bump Version"
on:
  push:
    branches:
      - "master"
jobs:
  draft-release:
    name: "Draft Release"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump SemVer
        id: bump-semver
        uses: paulhatch/semantic-version@v5.4.0
        with: 
          tag_prefix: "v"
          bump_each_commit: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump-semver.outputs.version_tag }}
          name: ${{ steps.bump-semver.outputs.version_tag }}
          draft: false
          prerelease: false
